import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { LandingNavbarComponent } from "../../ui/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LandingNavbarComponent
          title="SpeditIt"
          background={"primary"}
          size="md"
        />
        {children}
      </body>
    </html>
  );
}
